#==============================================#
# Corpse Spawn by RedSMURF: Configuration file #
#==============================================#

# To add a new corpse, follow the example below
# [Corpse Name]
# CORPSE_MODEL                  = Path of corpse's model
# CORPSE_FLAGS                  = a - Solid         b - Anim             c - Message            d - Sound
# CORPSE_TEAM                   = 0 - Disabled      1 - Terrorist Only,  2 - CT Only,           3 - Both Teams

# CORPSE_SEQUENCE               = Animation sequence for the corpse model
# CORPSE_FRAMERATE              = Animation frame rate for the corpse model
# CORPSE_SPAWN_CHANCE           = Corpse's respawn probability (0.0 = never, 1.0 = always)
# CORPSE_MESSAGE                = Message to display when the corpse is interacted with
# CORPSE_SOUND                  = Path to the sound file for the corpse
# CORPSE_SOUND_COOLDOWN         = Minimum - Maximum cooldown time for the corpse's sound

# To make an corpse available in the menu, you must defined at least it's name like this [Alien]
# corpse model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/CorpseSpawn/alien.mdl
SETTING_DEFAULT_FLAGS           = ac
SETTING_DEFAULT_TEAM            = 3

SETTING_DEFAULT_FRAMERATE       = 1.0
SETTING_DEFAULT_SEQUENCE        = 0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0
SETTING_DEFAULT_MESSAGE         = "\yWhat up"
SETTING_DEFAULT_MESSAGE         = "\dWhat you're doing here"
SETTING_DEFAULT_MESSAGE_TIMEOUT = 4 7
SETTING_DEFAULT_SOUND           = nihilanth/nil_die.wav
SETTING_DEFAULT_SOUND_COOLDOWN  = 10.0 15.0

SETTING_CORPSE_LOAD             = 1             # Whether to load saved corpses data of the current map
SETTING_CORPSE_RANGE            = 100.0         # Default range for corpse interaction
SETTING_OFFSET_BASE             = 120.0         # Default forward offset when previewing corpse placement
SETTING_OFFSET                  = 65.0 900.0    # Default minimum and maximum offset from the player to the corpse (MIN MAX)
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move corpse forward/backward
SETTING_OFFSET_FREQ             = 0.1           # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1           # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 120           # Transparency level of the ghost preview model (0 - 255)

SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav

SETTING_COLOR_SELECT            = 0 255 0

[Body Gib]
CORPSE_MODEL                    = models/CorpseSpawn/bodygib.mdl
CORPSE_MINS                     = -12 -30 0
CORPSE_MAXS                     = 12 35 12

[Bum hang]
CORPSE_MODEL                    = models/CorpseSpawn/bumhang.mdl
CORPSE_MINS                     = -15 -15 -10
CORPSE_MAXS                     = 15 15 70

[Butch dead]
CORPSE_MODEL                    = models/CorpseSpawn/butch_dead.mdl
CORPSE_MINS                     = -45 -25 0
CORPSE_MAXS                     = 45 25 45
CORPSE_FLAGS                    = abcd
CORPSE_MESSAGE                  = "\d[LOG: CASE 882 - GURNEY]^n\yENTRY 1: \dSubject found scratching at throat.^nWhispering about 'noises in the walls.'^nStrapped to bed. Given max neurotoxins.^nVitals climbing. Didn't blink for 48h.^n^n\yENTRY 2: \dMidnight. Skin grew paper-thin.^nBlack pulsing veins visible.^nJaw unhinged with a heavy crack.^nReleased dark spores into doctor's face.^nScreams lasted twenty minutes.^n^n\rENTRY 3: \dFacility went dark. Flatlining.^nYet... ribcage is still expanding.^nRestraints are completely frayed.^n\rDO NOT TOUCH BED. INCUBATION OVER."
CORPSE_SOUND                    = scientist/cantbeworse.wav
CORPSE_SOUND                    = scientist/cough.wav
CORPSE_SOUND                    = scientist/goodtoseeyou.wav
CORPSE_SOUND_COOLDOWN           = 7.0 12.0

[Cadaver-Open]
CORPSE_MODEL                    = models/CorpseSpawn/cadaver-open.mdl
CORPSE_MINS                     = -32 -12 0
CORPSE_MAXS                     = 32 12 12

[Cadaver 2]
CORPSE_MODEL                    = models/CorpseSpawn/cadaver2.mdl
CORPSE_MINS                     = -20 -20 0
CORPSE_MAXS                     = 25 15 75

[Freeman dead]
CORPSE_MODEL                    = models/CorpseSpawn/cinematic_freeman_dead.mdl
CORPSE_MINS                     = -30 -20 0
CORPSE_MAXS                     = 35 20 12

[Freeman welcome]
CORPSE_MODEL                    = models/CorpseSpawn/cinematic_freeman_welcome.mdl
CORPSE_MINS                     = -10 -15 0
CORPSE_MAXS                     = 15 15 75
CORPSE_FLAGS                    = abcd
CORPSE_MESSAGE                  = "\rHome Sweet Home"
CORPSE_SOUND                    = nihilanth/nil_die.wav
CORPSE_SOUND                    = nihilanth/nil_alone.wav
CORPSE_SOUND                    = nihilanth/nil_last.wav
CORPSE_SOUND_COOLDOWN           = 7.0 12.0

[Colonel tied]
CORPSE_MODEL                    = models/CorpseSpawn/colonel_tied.mdl
CORPSE_MINS                     = -32 -28 0
CORPSE_MAXS                     = 32 28 12
CORPSE_FLAGS                    = abcd
CORPSE_SOUND                    = barney/c2a5_ba_helpme.wav

[Colonel dead]
CORPSE_MODEL                    = models/CorpseSpawn/colonel_tied.mdl
CORPSE_MINS                     = -32 -28 0
CORPSE_MAXS                     = 32 28 12
CORPSE_SEQUENCE                 = 2

[Corpse Female 1]
CORPSE_MODEL                    = models/CorpseSpawn/corpse_female01.mdl
CORPSE_MINS                     = -12 -32 0
CORPSE_MAXS                     = 27 27 12

[Corpse Female 2]
CORPSE_MODEL                    = models/CorpseSpawn/corpse_female02.mdl
CORPSE_MINS                     = -18 -25 0
CORPSE_MAXS                     = 22 32 15

[Corpse Male 1 Low Spawn]
CORPSE_MODEL                    = models/CorpseSpawn/corpse_male01.mdl
CORPSE_MINS                     = -45 -22 0
CORPSE_MAXS                     = 28 25 12
CORPSE_SPAWN_CHANCE             = 0.2

[Corpse Male 2 Mid Spawn]
CORPSE_MODEL                    = models/CorpseSpawn/corpse_male02.mdl
CORPSE_MINS                     = -15 -15 0
CORPSE_MAXS                     = 32 25 32
CORPSE_SPAWN_CHANCE             = 0.5

[Corpse Male 3 Always Spawn]
CORPSE_MODEL                    = models/CorpseSpawn/corpse_male03.mdl
CORPSE_MINS                     = -28 -25 0
CORPSE_MAXS                     = 38 22 12

[Corpse Artic]
CORPSE_MODEL                    = models/CorpseSpawn/corpse3.mdl
CORPSE_MINS                     = -52 -18 0
CORPSE_MAXS                     = 25 35 12
CORPSE_MESSAGE                  = "\yDyatlov Pass Incident, 1959."
CORPSE_MESSAGE                  = "\dThe tent was ripped open from the inside out."
CORPSE_MESSAGE                  = "\rThey fled barefoot into the freezing dark."

[Corpse Grunt 1]
CORPSE_MODEL                    = models/CorpseSpawn/corpse4.mdl
CORPSE_MINS                     = -32 -12 0
CORPSE_MAXS                     = 25 25 12
CORPSE_FLAGS                    = abcd
CORPSE_MESSAGE                  = "\rmy... ass... is heavy..."
CORPSE_SOUND                    = hgrunt/bastard.wav
CORPSE_SOUND                    = hgrunt/damn.wav
CORPSE_SOUND                    = hgrunt/freeman!.wav
CORPSE_SOUND                    = hgrunt/squad!.wav
CORPSE_SOUND_COOLDOWN           = 5.0 10.0

[Corpse Grunt 2]
CORPSE_MODEL                    = models/CorpseSpawn/corpse6.mdl
CORPSE_MINS                     = -35 -15 0
CORPSE_MAXS                     = 35 28 12
CORPSE_FLAGS                    = abcd
CORPSE_MESSAGE                  = "\rmy... ass... is heavy..."
CORPSE_SOUND                    = hgrunt/bastard.wav
CORPSE_SOUND                    = hgrunt/damn.wav
CORPSE_SOUND                    = hgrunt/freeman!.wav
CORPSE_SOUND                    = hgrunt/squad!.wav
CORPSE_SOUND_COOLDOWN           = 5.0 10.0

[Houndeye]
CORPSE_MODEL                    = models/CorpseSpawn/corpse7.mdl
CORPSE_MINS                     = -27 -22 0
CORPSE_MAXS                     = 22 22 17

[Alien]
CORPSE_MODEL                    = models/CorpseSpawn/alien.mdl
CORPSE_MINS                     = -35 -20 0
CORPSE_MAXS                     = 35 30 12
CORPSE_MESSAGE                  = "\yRoswell, 1947."
CORPSE_MESSAGE                  = "\dThe government called it a weather balloon."
CORPSE_MESSAGE                  = "\rThe autopsy records say otherwise."

[Corpse Scientist 1]
CORPSE_MODEL                    = models/CorpseSpawn/corpse9.mdl
CORPSE_MINS                     = -25 -15 0
CORPSE_MAXS                     = 22 18 12
CORPSE_MESSAGE                  = "\dLouis Slotin - May 21, 1946."
CORPSE_MESSAGE                  = "\yThe screwdriver slipped, and the room glowed blue."
CORPSE_MESSAGE                  = "\rHe shielded his assistants from the Demon Core."

[Corpse Scientist 2]
CORPSE_MODEL                    = models/CorpseSpawn/corpse13.mdl
CORPSE_MINS                     = -15 -32 0
CORPSE_MAXS                     = 18 28 1

[Half Corpse]
CORPSE_MODEL                    = models/CorpseSpawn/halfCorpse.mdl
CORPSE_MINS                     = -22 -27 0
CORPSE_MAXS                     = 25 22 12
CORPSE_MESSAGE                  = "\rThe Black Dahlia case, 1947."
CORPSE_MESSAGE                  = "\dThe body was severed cleanly at the waist."

[Dead Body]
CORPSE_MODEL                    = models/CorpseSpawn/dead_body.mdl
CORPSE_MINS                     = -15 -15 -75
CORPSE_MAXS                     = 15 15 22

[Dead Kid]
CORPSE_MODEL                    = models/CorpseSpawn/dead_kid.mdl
CORPSE_MINS                     = -5 -15 0
CORPSE_MAXS                     = 32 15 28

[Dead Horse]
CORPSE_MODEL                    = models/CorpseSpawn/deadhorse.mdl
CORPSE_MINS                     = -12 -52 0
CORPSE_MAXS                     = 32 32 22

[Icebox Body]
CORPSE_MODEL                    = models/CorpseSpawn/AF_icebox_body.mdl
CORPSE_MINS                     = -15 -52 0
CORPSE_MAXS                     = 15 37 12

[Baboon]
CORPSE_MODEL                    = models/CorpseSpawn/baboon.mdl
CORPSE_MINS                     = -7 -7 -22
CORPSE_MAXS                     = 7 12 7
CORPSE_FLAGS                    = abc
CORPSE_SEQUENCE                 = 0

[Body Bag]
CORPSE_MODEL                    = models/CorpseSpawn/bodybag.mdl
CORPSE_MINS                     = -37 -12 0
CORPSE_MAXS                     = 37 12 12

[Murdered Body]
CORPSE_MODEL                    = models/CorpseSpawn/cc_murdered_body.mdl
CORPSE_MINS                     = -9 -9 0
CORPSE_MAXS                     = 9 9 90

[Coffin]
CORPSE_MODEL                    = models/CorpseSpawn/coffin.mdl
CORPSE_MINS                     = -42 -18 0
CORPSE_MAXS                     = 45 15 17

[Imp]
CORPSE_MODEL                    = models/CorpseSpawn/d3_imp.mdl
CORPSE_MINS                     = -22 -12 0
CORPSE_MAXS                     = 17 12 22

[Headcrab Front]
CORPSE_MODEL                    = models/CorpseSpawn/dead_headcrab.mdl
CORPSE_MINS                     = -12 -12 0
CORPSE_MAXS                     = 12 12 12
CORPSE_SEQUENCE                 = 0

[Headcrab Back]
CORPSE_MODEL                    = models/CorpseSpawn/dead_headcrab.mdl
CORPSE_MINS                     = -12 -12 0
CORPSE_MAXS                     = 12 12 12
CORPSE_SEQUENCE                 = 1

[Headcrab 2]
CORPSE_MODEL                    = models/CorpseSpawn/dead_headcrab2.mdl
CORPSE_MINS                     = -12 -12 0
CORPSE_MAXS                     = 12 12 12

[Dead Zombie 1]
CORPSE_MODEL                    = models/CorpseSpawn/deadzombie2.mdl
CORPSE_MINS                     = -32 -9 0
CORPSE_MAXS                     = 29 9 15

[Dead Zombie 2]
CORPSE_MODEL                    = models/CorpseSpawn/deadzombie3.mdl
CORPSE_MINS                     = -9 -9 0
CORPSE_MAXS                     = 12 12 42

[Eaten]
CORPSE_MODEL                    = models/CorpseSpawn/eaten.mdl
CORPSE_MINS                     = -9 -12 0
CORPSE_MAXS                     = 18 12 42
CORPSE_SEQUENCE                 = 0

[Slave]
CORPSE_MODEL                    = models/CorpseSpawn/fordslave.mdl
CORPSE_MINS                     = -42 -15 0
CORPSE_MAXS                     = 47 15 19

[Geo Alpha]
CORPSE_MODEL                    = models/CorpseSpawn/geo_alpha_dead.mdl
CORPSE_MINS                     = -15 -32 0
CORPSE_MAXS                     = 12 27 17

[Geo Stol Trup]
CORPSE_MODEL                    = models/CorpseSpawn/geo_stol_trup.mdl
CORPSE_MINS                     = -15 -52 0
CORPSE_MAXS                     = 15 37 50

[Hanged Nerd]
CORPSE_MODEL                    = models/CorpseSpawn/hangednerd.mdl
CORPSE_MINS                     = -12 -12 12
CORPSE_MAXS                     = 12 12 92

[Headless Zombie]
CORPSE_MODEL                    = models/CorpseSpawn/headless_zombie.mdl
CORPSE_MINS                     = -45 -17 0
CORPSE_MAXS                     = 22 12 17

[Corpse Burned]
CORPSE_MODEL                    = models/CorpseSpawn/me3_CorpseBurnt02.mdl
CORPSE_MINS                     = -9 -32 0
CORPSE_MAXS                     = 12 57 12

[Corpse Tarp]
CORPSE_MODEL                    = models/CorpseSpawn/me3_CorpseTarp01.mdl
CORPSE_MINS                     = -22 -45 0
CORPSE_MAXS                     = 22 42 12

[Dead Dog]
CORPSE_MODEL                    = models/CorpseSpawn/rock_deaddog.mdl
CORPSE_MINS                     = -32 -25 0
CORPSE_MAXS                     = 42 25 22

[Skel]
CORPSE_MODEL                    = models/CorpseSpawn/skel.mdl
CORPSE_MINS                     = 0 -7 -19
CORPSE_MAXS                     = 12 7 32

[Skeleton]
CORPSE_MODEL                    = models/CorpseSpawn/skeleton.mdl
CORPSE_MINS                     = -42 -12 0
CORPSE_MAXS                     = 42 12 12

[Skeleton Meat]
CORPSE_MODEL                    = models/CorpseSpawn/skeleton_meat.mdl
CORPSE_MINS                     = -12 -17 0
CORPSE_MAXS                     = 12 12 25

[Cutoff Legs]
CORPSE_MODEL                    = models/CorpseSpawn/sub_cutoff_legs.mdl
CORPSE_MINS                     = -42 -9 0
CORPSE_MAXS                     = 3 9 12

[Ut2k4 Victim]
CORPSE_MODEL                    = models/CorpseSpawn/ut2k4_victim.mdl
CORPSE_MINS                     = -5 -15 0
CORPSE_MAXS                     = 12 15 52








